[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Librerías necesarias
lib_deps = 
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8
    Wire
    SPI

; Configuración de compilación
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1

; Opciones de upload
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
